version: 2

sources:
  - name: SNOWFLAKE_SOURCE
    description: "Sample dataset"
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL
    tables:
      - name: STORE_SALES
        description: "Sales store details"
      